project_id = "wgubtalkareywkwitktb"

[functions.transcript]
verify_jwt = false

[functions.ai-modmail-reply]
verify_jwt = false

[functions.auto-create-bot]
verify_jwt = false

[functions.discord-interactions]
verify_jwt = false

