spec:
  name: modmail-bot
  region: fra
  workers:
    - name: bot
      source_dir: bot
      github:
        repo: your-github-user/your-repo
        branch: main
        deploy_on_push: true
      environment_slug: node-js
      instance_size_slug: basic-xxs
      instance_count: 1
      run_command: node src/index.js
      envs:
        - key: DISCORD_BOT_TOKEN
          scope: RUN_TIME
          type: SECRET
        - key: SUPABASE_URL
          scope: RUN_TIME
          value: https://wgubtalkareywkwitktb.supabase.co
        - key: SUPABASE_SERVICE_ROLE_KEY
          scope: RUN_TIME
          type: SECRET
        - key: BOT_ID
          scope: RUN_TIME
          value: ""
